
services:
  db:
    image: postgres:15
    container_name: sport_db
    environment:
      POSTGRES_USER: athlete
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: tracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U athlete -d tracker_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: sport_flask
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app  

volumes:
  postgres_data: